"""baseline

Revision ID: c351e4078146
Revises: 
Create Date: 2026-04-27 22:58:19.155381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c351e4078146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('timed_out', sa.Integer(), nullable=False),
    sa.Column('upload_key', sa.String(length=256), nullable=True),
    sa.Column('original_filename', sa.String(length=128), nullable=True),
    sa.Column('original_content_type', sa.String(length=64), nullable=True),
    sa.Column('original_size_bytes', sa.Integer(), nullable=True),
    sa.Column('stored_size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_expires_at', 'jobs', ['expires_at'], unique=False)
    op.create_index('ix_jobs_state', 'jobs', ['state'], unique=False)
    op.create_index('ix_jobs_user_id', 'jobs', ['user_id'], unique=False)
    op.create_table('results',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('confidence_label', sa.String(length=64), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_id', name='uq_results_job_id')
    )
    op.create_index('ix_results_job_id', 'results', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_results_job_id', table_name='results')
    op.drop_table('results')
    op.drop_index('ix_jobs_user_id', table_name='jobs')
    op.drop_index('ix_jobs_state', table_name='jobs')
    op.drop_index('ix_jobs_expires_at', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
